### ISSUE TITLE
localsearch seems broken with mkdocs-material 7.0.0 update

### ISSUE THREAD

**Issue by renoger** [wilhelmer/mkdocs-localsearch#12]
Hi @wilhelmer,

Thanks for your continued support on the plugin! 

I´ve updated to localsearch 0.8.0 and followed your guidance (added {{ super() }} in the custom main.html).
Since I´ve updated to material 7.0.0 (and 7.0.1) the localsearch is not working for me anymore. The search-index is created but the search box doesn´t open when active:
![image](https://user-images.githubusercontent.com/62448529/109155188-92a08280-776f-11eb-8193-fe4abbc49b9f.png)

It works fine with material 6.2.8 and the identical configuration though:
![image](https://user-images.githubusercontent.com/62448529/109154811-1b6aee80-776f-11eb-9033-ec9e9d53fa47.png)

I wonder if it breaks due to the changes in base.html or general architectural oberhaul of material v7.
Any idea what I´m missing or how I can debug?

Thanks
René

**Comment by wilhelmer** [comment]
Did you customize your header? If so, you must update your header.html to Material's latest version (see https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/header.html).

**Comment by renoger** [comment]
I previously used a custom header, but not anymore. To make sure I don´t overwrite anything I removed the whole partials folder and left the main.html as my only custom file. But it doesn´t affect the issue.

**Comment by wilhelmer** [comment]
I tested it with the beta, not with the final version. I'll look into it later, thanks for reporting.

**Comment by renoger** [comment]
Good point, I was just checking 7.0.0b1 and 7.0.0b2 which worked fine. 
So please check if you see the same behaviour with the final version (which is 7.0.2 by now, also not working for me). Thanks!

**Comment by wilhelmer** [comment]
@squidfunk Did you change anything here between v7 beta and final? I can see `__search` is being fulfilled correctly, but search doesn't work, as described above.

<img width="549" alt="Bildschirmfoto 2021-03-01 um 14 23 27" src="https://user-images.githubusercontent.com/2234833/109502810-c2b29300-7a99-11eb-96c3-659d09e768be.png">

**Comment by squidfunk** [comment]
Should work. Could you file an issue with a reproducible example?

**Comment by wilhelmer** [comment]
Done, thanks for your help.

**Comment by wilhelmer** [comment]
Fixed in MkDocs Material 7.0.4.
