### ISSUE TITLE
Customized search query transformation of Material and localsearch not work

### ISSUE THREAD

**Issue by MtShan** [wilhelmer/mkdocs-localsearch#13]
Following the [official instruction](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#query-transformation), I customized search query transformation, and then local search does not work well.

Workaround is:
1. Open 'site/search/search_index.js' and delete the last part of the file. So, I deleted 
```js
"; var __search = { index: Promise.resolve(local_index) }"
```
2. Open ' theme/main.html' and add this line:
```js
index: Promise.resolve(local_index),
```
So, content of ' theme/main.html' is:

```html
{% extends "base.html" %}
{% block config %}
{{ super() }}
{% if "localsearch" in config["plugins"] %}
<script src="{{ 'assets/javascripts/iframe-worker.js' | url }}"></script>
<script src="{{ 'search/search_index.js' | url }}"></script>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/tiny-segmenter@0.2.0/dist/tiny-segmenter-0.2.0.min.js"></script>
<script>
var __search = {
    index: Promise.resolve(local_index),
    transform: function(query) {
        var segmenter = new TinySegmenter();
        var segs = segmenter.segment(query);
        var newQuery = segs.join(" ");
        console.log(newQuery);
        return newQuery;
    }
}
</script>
{% endblock %}
```
My Environment is:

mkdocs==1.1.2
mkdocs-material==7.1.4

**Comment by wilhelmer** [comment]
As @squidfunk [pointed out](https://github.com/wilhelmer/mkdocs-localsearch/pull/16#issuecomment-847574055), you should be able to do this like this, without modifying the plugin or `search_index.js`:

```js
{% extends "base.html" %}
{% block config %}
{{ super() }}
{% if "localsearch" in config["plugins"] %}
<script src="{{ 'assets/javascripts/iframe-worker.js' | url }}"></script>
<script src="{{ 'search/search_index.js' | url }}"></script>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/tiny-segmenter@0.2.0/dist/tiny-segmenter-0.2.0.min.js"></script>
<script>
    __search.transform = function(query) {
        var segmenter = new TinySegmenter();
        var segs = segmenter.segment(query);
        var newQuery = segs.join(" ");
        console.log(newQuery);
        return newQuery;
      }
</script>
{% endblock %}
```

Could you try if that works for you? Thanks!

**Comment by MtShan** [comment]
Dear Mr. wilhelmer,
Thank you so much about your advice. Your advice is exactly correct. My issue is instantaneously solved by your advice.
I was amateur and I was wrong. I am so sorry to bother you.
