### ISSUE TITLE
Error due to CORS policy 

### ISSUE THREAD

**Issue by kamaing** [wilhelmer/mkdocs-localsearch#20]
Dear Developers,

I encountered a problem when implementing local search.
I received the following error:
![Error_CORS_policy](https://user-images.githubusercontent.com/37227939/174550347-a0e3613b-78de-40a3-a1d8-9ffb231e2d76.png)

I am using following versions:
- mkdocs, Version 1.3.0
- mkdocs-material, Version: 8.3.5

Many Thanks. I like your project.

**Comment by wilhelmer** [comment]
This is the standard error you will get when the plugin is **not** installed. Try reinstalling the plugin as described in the [Readme](https://github.com/wilhelmer/mkdocs-localsearch/blob/master/README.md) file.

**Comment by kamaing** [comment]
Hello [wilhelmer](https://github.com/wilhelmer),

this seems not to be the case. The plugin is installed and the build is carried out.
Nevertheless, the error is still present.

It seems that mkdocs is not able to fetch the json file from the local file system.

**Comment by wilhelmer** [comment]
If the plugin is properly installed, then there is no JSON. The plugin replaces `search/search_index.json` with `search/search_index.js`, which then can be fetched locally.

So if `/site/search/search_index.json` exists in your output, the plugin is not properly installed.

**Comment by kamaing** [comment]
Thanks, it worked for me.
I did edit the files in the overrides folder, before.

After editing the files in the root directory of the theme, it worked.

**Comment by wilhelmer** [comment]
Great :-) Glad I could help.
