### ISSUE TITLE
Different search configuration for mkdocs-material 5

### ISSUE THREAD

**Issue by squidfunk** [wilhelmer/mkdocs-localsearch#3]
This is just an FYI that the final way search is configured changed with https://github.com/squidfunk/mkdocs-material/commit/635343544e3c72b5980547e0787b4dd7ae8b5c90. The new format is:

``` jinja
{% block config %}
  <script>
    var search = {
      index: Promise.resolve(idxJson)
    }
  </script>
{% endblock %}
```

This makes merging search configuration into the final config simpler and limits the way stuff can break, so it should essentially be more stable.

**Comment by wilhelmer** [comment]
Thanks for the info. I'll update the plugin as soon as the final version of Material 5 is out.

**Comment by squidfunk** [comment]
Released as part of RC 4.

**Comment by wilhelmer** [comment]
Fixed with version 0.7.0.

**Comment by renoger** [comment]
Hi @wilhelmer, I noticed that your plugin wasn´t working with RC4 any longer so i found this thread and saw that you´ve updated yesterday. However, I can´t seem to install your 0.7.0. as pip install wouldn´t find it. Any ideas? Thanks!

**Comment by wilhelmer** [comment]
Sorry, forgot to upload the package to PyPI. Should be available via `pip install` now.

**Comment by renoger** [comment]
great, it works again! Thank you
