### ISSUE TITLE
Search does not work on pages that are not in the main folder

### ISSUE THREAD

**Issue by AdamCooman** [wilhelmer/mkdocs-localsearch#5]
Suppose that I have the following structure in my docs folder:

```
site
    homepage.md
    SubFolder
        subpage.md
```

then the search works on the generated `homepage.html`, but it does not work on the generated `subpage.html`.

Inspection with chrome finds that, on `subpage.html`, we try to load `site/SubFolder/search/search_index.js` which does not exist because the search index is located at `site/search/search_index.js`.

Is there a bug that causes this, or am I configuring something wrong?

**Comment by tjapro** [comment]
Hello @AdamCooman. The pull request https://github.com/wilhelmer/mkdocs-localsearch/pull/4 explains that. Thanks.

**Comment by wilhelmer** [comment]
Yes, please try the new code shown in steps 4 and 5 of the README and check if the problem persists. Thanks!

**Comment by AdamCooman** [comment]
I did step 4, but not step 5, because I have an internet connection. I added step 5, but it did not resolve the issue.

The html code that is inserted into each page is the following now:
```
<script src="../assets/javascripts/iframe-worker.js"></script>
<script src="search/search_index.js"></script>
```

For a file in a subfolder, that second one needs to be `../search/search_index.js`

**Comment by AdamCooman** [comment]
Ok, I fixed it, the code I had in my main.html was different from the one in the current readme.
the `| url` part was missing.
Sorry for the inconvenience
