### ISSUE TITLE
Search results miss index.html filename in URL (wont work offline)

### ISSUE THREAD

**Issue by jsteinhofff** [wilhelmer/mkdocs-localsearch#8]
I just tried the offline capability of mkdocs-localsearch , and while the search seems to work nicely, following the search results does not work because the filename "index.html" is missing in the URL. This is not an issue when running a server because it will automatically serve index.html when no filename is in the URL, but when using the search offline, i will see the folder index instead.
I had a look at search_index.js, and it seems that the "location" field is already empty / just contains the anchor but not the filename.
Still i am not sure if this should be reported to mkdocs itself, because it has no offline-search in scope, so i fear it would be necessary to post-process the search-index before writing it to the javascript file.

What do you think?

Installed dependencies are:
```
click==7.1.2
future==0.18.2
importlib-metadata==1.7.0
Jinja2==2.11.2
joblib==0.14.1
livereload==2.6.3
lunr==0.5.8
Markdown==3.2.2
MarkupSafe==1.1.1
mkdocs==1.1.2
mkdocs-localsearch==0.7.0
mkdocs-material==5.5.12
mkdocs-material-extensions==1.0
nltk==3.5
Pygments==2.6.1
pymdown-extensions==8.0
PyYAML==5.3.1
regex==2020.7.14
six==1.15.0
tornado==6.0.4
tqdm==4.48.2
zipp==1.2.0
```

**Comment by wilhelmer** [comment]
Is [`use_directory_urls`](https://www.mkdocs.org/user-guide/configuration/#use_directory_urls) set to `false` in your `mkdocs.yml`? This is a must-have for projects that are running locally.

**Comment by jsteinhofff** [comment]
Hi @wilhelmer , thanks for the immediate and helpful answer, my bad!
Created PR #9 to add a hint in the README.ml.
